theme: jekyll-theme-cayman
title: SmmServer
description: Open source private server for Super Mario Maker (Wii U), integrated with SMMDB and Cemu
download: https://mega.nz/file/jgJF2SxQ#-nH5PAu2P3Tu1GNaiIRgd37gzv1JdzfciN0llxMwdOw
